python-interpreter-path = "backend/.venv/bin/python"

project-includes = ["backend/**/*.py", "database/**/*.py"]
project-excludes = ["**/.venv/**", "**/__pycache__/**"]

search-path = ["backend", "."]

[[sub-config]]
matches = "database/models/*.py"
[sub-config.errors]
bad-override = false
